[pytest]

# Minimum version of pytest required to run these tests
minversion = 7.0

# Command-line arguments automatically added to every execution
addopts = -ra -v --strict-markers --tb=short

# Explicitly define directories where pytest should look for tests
testpaths = validation